site_name: 'The Graphic Rustication Company - Under Construction'
site_url: 'http://graphicrustication.com'
markdown: rdiscount
rdiscount:
    extensions: [smart]
permalink: /articles/:title
paginate: 3